config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :rooms
  resources :admins
  resources :libraryusers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'static_pages#home'
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
  get '/static_pages_aboutus', to: 'static_pages#aboutus'
  get '/static_pages_contactus', to: 'static_pages#contactus'

  get    '/login_admin',   to: 'sessions#adminLogin'
  post   '/login_admin',   to: 'sessions#create_admin'
  delete '/logout_admin',  to: 'sessions#destroy_admin'
  get '/logout_admin', to: 'sessions#destroy_admin'

  get '/destroy_booking/:id', to: 'bookings#destroy', as: 'destroy_booking'

  get '/destroy_libraryuser/:id', to: 'libraryusers#destroy', as: 'destroy_libraryuser'

  get '/destroy_admin/:id', to: 'admins#destroy', as: 'destroy_admin'

   get '/destroy_room/:id', to: 'rooms#destroy', as: 'destroy_room'

  get 'static_pages/home'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
        <%=link_to image_tag("//www.lib.ncsu.edu/sites/all/themes/ncsulib_foundation/images/ncsu-library-logo-white.png", border: 0), {action: 'home', controller: 'static_pages'}, {class: 'dock-item ncsuLibLogoClass'}%>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right classbtnSep">
        <%= button_to "Home", static_pages_home_path,
                      :class => "btn btn-default navbar-btn btnSep", :method => :get %>
        <%= button_to "About Us!", static_pages_aboutus_path,
                      :class => "btn btn-default navbar-btn btnSep", :method => :get %>
        <%= button_to "Contact Us!", static_pages_contactus_path,
                      :class => "btn btn-default navbar-btn btnSep", :method => :get %>
        <% if admin_logged_in?%>
            <%= button_to "Logout", logout_admin_path,
                          :class => "btn btn-default navbar-btn btnSep", :method => :get %>
        <% end %>
        <% if libraryuser_logged_in?%>
            <%= button_to "Logout", logout_path,
                          :class => "btn btn-default navbar-btn btnSep", :method => :get %>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/static_pages/aboutus.html.erb
<!-- Introduction Row -->
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">About Us
      <small>Thank you for visiting our page!</small>
    </h1>
    <p>We are developing Ruby on rails for CSC 517 project. This app is library room management. Please login using admin@ncsu.edu</p>
  </div>
</div>

<!-- Team Members Row -->
<div class="row">
  <div class="col-lg-12">
    <h2 class="page-header">Our Team</h2>
  </div>
  <div class="col-lg-4 col-sm-6 text-center">
    <img class="img-circle img-responsive img-center" src="https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAdRAAAAJDk4Y2Q2Y2Y2LTFlMDUtNGQxNC1iOTUxLTM4MDc4NzY1ZmY4YQ.jpg" alt="">
    <h3>Mahesh Masale
      <small>Decoder!</small>
    </h3>
    <p>Looks after DJ and Pranav!</p>
  </div>
  <div class="col-lg-4 col-sm-6 text-center">
    <img class="img-circle img-responsive img-center" src="https://media.licdn.com/media/AAEAAQAAAAAAAAhHAAAAJGIzYzMyMjc3LWIyMDctNDhlYS04YWUxLWQxNjcwYzMxZDkyOA.jpg" alt="">
    <h3>Pramav Nawathe
      <small>Dungen Master!</small>
    </h3>
    <p>Login Master!</p>
  </div>
  <div class="col-lg-4 col-sm-6 text-center">
    <img class="img-circle img-responsive img-center" src="https://media.licdn.com/media/AAEAAQAAAAAAAAk2AAAAJGY3ZmI3NDEyLTdkM2EtNDU2ZS05Y2I2LTUyN2FjZjY0NjhlYg.jpg" alt="">
    <h3>Dhananjay Sathe
      <small>The Coder!   </small>
    </h3>
    <p>Busy in coding competition!</p>
  </div>
</div>

app/views/static_pages/contactus.html.erb
<div class="jumbotron jumbotron-sm">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-lg-12">
        <h1 class="h1">
          Contact us <small>Feel free to contact us</small></h1>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class="well well-sm">
        <form>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label for="name">
                  Name</label>
                <input type="text" class="form-control" id="name" placeholder="Enter name" required="required" />
              </div>
              <div class="form-group">
                <label for="email">
                  Email Address</label>
                <div class="input-group">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span>
                                </span>
                  <input type="email" class="form-control" id="email" placeholder="Enter email" required="required" /></div>
              </div>
              <div class="form-group">
                <label for="subject">
                  Subject</label>
                <select id="subject" name="subject" class="form-control" required="required">
                  <option value="na" selected="">Choose One:</option>
                  <option value="service">General Customer Service</option>
                  <option value="suggestions">Suggestions</option>
                  <option value="product">Product Support</option>
                </select>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label for="name">
                  Message</label>
                <textarea name="message" id="message" class="form-control" rows="9" cols="25" required="required"
                          placeholder="Message"></textarea>
              </div>
            </div>
            <div class="col-md-12">
              <button type="submit" class="btn btn-primary pull-right" id="btnContactUs">
                Send Message</button>
            </div>
          </div>
        </form>
      </div>
    </div>
    <div class="col-md-4">
      <form>
        <legend><span class="glyphicon glyphicon-globe"></span> Our office</legend>
        <address>
          <strong>Maraths, Inc.</strong><br>
          456 Awesome Ave, leave it 600<br>
          Non City YYL, NC 784512<br>
          <abbr title="Phone">
            P:</abbr>
          (000) 000-0000
        </address>
        <address>
          <strong>Full Name</strong><br>
          <a href="mailto:#">loDontSendEmail@email.com</a>
        </address>
      </form>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<% if !libraryuser_logged_in? &&  !admin_logged_in?%>
    <div class="center jumbotron">
      <h1>Welcome to Library Room Booking App</h1>
      <%= link_to "Admin Login" , login_admin_path, class: "btn btn-lg btn-default" %>
      <%= link_to "Library User Login" , login_path, class: "btn btn-lg btn-default" %>
      <%= link_to "New to Library => Signup!" , new_libraryuser_path, class: "btn btn-lg btn-default" %>
    </div>

<% end %>
<% if admin_logged_in? %>
    <div class="center jumbotron">
      <h1>Welcome Admin</h1>
      <h2><%= link_to "Edit Profile",  edit_admin_path(session[:admin_id]), class: "btn btn-block btn-default"%></h2>
      <h2><%= link_to "Manage Admins", admins_path, class: "btn btn-block btn-default" %></h2>
      <h2><%= link_to "Manage Users", libraryusers_path, class: "btn btn-block btn-default"%></h2>
      <h2><%= link_to "Manage Rooms", rooms_path, class: "btn btn-block btn-default"%></h2>
      <h2><%= link_to "Bookings", bookings_path, class: "btn btn-block btn-default"%></h2>

    </div>
<% end %>
<% if libraryuser_logged_in? %>
    <div class="center jumbotron">
      <h1>Welcome to Library Room Booking System</h1>
      <h2><%= link_to "View Rooms", rooms_path, class: "btn btn-block btn-default"%></h2>
      <h2><%= link_to "Book a Room", new_booking_path, class: "btn btn-block btn-default"%></h2>
      <h2><%= link_to "My Bookings", bookings_path, class: "btn btn-block btn-default"%></h2>
      <h2><%= link_to "Edit Profile",edit_libraryuser_path(session[:libraryuser_id]), class: "btn btn-block btn-default"%></h2>
    </div>
<% end %>