config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :rooms
  resources :admins
  resources :libraryusers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'static_pages#home'
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
  get '/static_pages_aboutus', to: 'static_pages#aboutus'
  get '/static_pages_contactus', to: 'static_pages#contactus'

  get    '/login_admin',   to: 'sessions#adminLogin'
  post   '/login_admin',   to: 'sessions#create_admin'
  delete '/logout_admin',  to: 'sessions#destroy_admin'
  get '/logout_admin', to: 'sessions#destroy_admin'

  get '/destroy_booking/:id', to: 'bookings#destroy', as: 'destroy_booking'

  get '/destroy_libraryuser/:id', to: 'libraryusers#destroy', as: 'destroy_libraryuser'

  get '/destroy_admin/:id', to: 'admins#destroy', as: 'destroy_admin'

   get '/destroy_room/:id', to: 'rooms#destroy', as: 'destroy_room'

  get 'static_pages/home'
end

app/models/libraryuser.rb
class Libraryuser < ApplicationRecord
	has_many :bookings, dependent: :destroy
	
	has_secure_password
	validates :name, presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

    validates :password_digest, presence: true, length: { minimum: 6 }
end

app/controllers/libraryusers_controller.rb
class LibraryusersController < ApplicationController
  before_action :set_libraryuser, only: [:show, :edit, :update, :destroy]
  before_action :authorize_either
  skip_before_action :authorize_either , only: [:new, :create]

  # GET /libraryusers
  # GET /libraryusers.json
  def index
    @libraryusers = Libraryuser.all
  end

  # GET /libraryusers/1
  # GET /libraryusers/1.json
  def show
  end

  # GET /libraryusers/new
  def new
    @libraryuser = Libraryuser.new
  end

  # GET /libraryusers/1/edit
  def edit
  end

  # POST /libraryusers
  # POST /libraryusers.json
  def create
    @libraryuser = Libraryuser.new(libraryuser_params)

    respond_to do |format|
      if @libraryuser.save
        format.html { redirect_to @libraryuser, notice: 'Libraryuser was successfully created.' }
        format.json { render :show, status: :created, location: @libraryuser }
      else
        format.html { render :new }
        format.json { render json: @libraryuser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libraryusers/1
  # PATCH/PUT /libraryusers/1.json
  def update
    respond_to do |format|
      if @libraryuser.update(libraryuser_params)
        format.html { redirect_to @libraryuser, notice: 'Libraryuser was successfully updated.' }
        format.json { render :show, status: :ok, location: @libraryuser }
      else
        format.html { render :edit }
        format.json { render json: @libraryuser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libraryusers/1
  # DELETE /libraryusers/1.json
  def destroy
    #if there are bookings in the name of deleted libraryuser, those bookings will be deleted
    @bookings = Booking.all
    @bookings = @bookings.where(libraryuser_id: @libraryuser.id)
    for eachBooking in @bookings
      destroy_booking_path eachBooking
    end

    @libraryuser.destroy
    respond_to do |format|
      format.html { redirect_to libraryusers_url, notice: 'Libraryuser was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_libraryuser
      @libraryuser = Libraryuser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def libraryuser_params
      params.require(:libraryuser).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/libraryusers_helper.rb
module LibraryusersHelper
end

app/views/libraryusers/_form.html.erb
<%= form_for(libraryuser) do |f| %>
  <% if libraryuser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(libraryuser.errors.count, "error") %> prohibited this libraryuser from being saved:</h2>

      <ul>
      <% libraryuser.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

    <div class="field">
      <%= f.label :password %>
      <%= f.text_field :password %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %>
      <%= f.text_field :password_confirmation %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/libraryusers/edit.html.erb
<h1>Editing Libraryuser</h1>

<%= render 'form', libraryuser: @libraryuser %>

<%= link_to 'Show', @libraryuser %> |
<%= link_to 'Back', root_path %>

app/views/libraryusers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Libraryusers</h1>

<table>
  <thead>
    <tr>
      <th>User ID</th>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @libraryusers.each do |libraryuser| %>
      <tr>
        <td><%= libraryuser.id%></td>
        <td><%= libraryuser.name %></td>
        <td><%= libraryuser.email %></td>
        <td><%= link_to 'Show', libraryuser %></td>
        <% if libraryuser_logged_in? %>
          <td>Logged</td>
          <td><%= link_to 'Edit', edit_libraryuser_path(libraryuser) %></td>
        <%end%>
        <td><%= link_to 'Destroy', destroy_libraryuser_path(libraryuser), data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Libraryuser', new_libraryuser_path %>

app/views/libraryusers/new.html.erb
<h1>New Libraryuser</h1>

<%= render 'form', libraryuser: @libraryuser %>

<%= link_to 'Back', libraryusers_path %>

app/views/libraryusers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @libraryuser.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @libraryuser.email %>
</p>

<h3>Booking history</h3>

<% @bookings = Booking.where(libraryuser_id: @libraryuser.id) %>


<table>
  <thead>
    <tr>
      <th>Room No</th>
      <th>Date</th>
      <th>Start time</th>
      <th>End time</th>
      <%if admin_logged_in? %>
        <th colspan="3"> Booked by </th>
      <% end -%> 
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.room.roomid %></td>
        <td><%= booking.date %></td>
        <td><%= booking.start_time.hour %>:00</td>
        <td><%= booking.start_time.hour+2 %>:00</td>
        <%if admin_logged_in? %>
          <td><%= link_to booking.libraryuser_id.to_s, 'libraryusers/'+booking.libraryuser_id.to_s%></td>
        <% end -%>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Cancel booking', destroy_booking_path(booking), data: {confirm: "Are you sure?"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%#= link_to 'Edit', edit_libraryuser_path(@libraryuser) %> 
<%#= link_to 'Back', root_path %>