config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :rooms
  resources :admins
  resources :libraryusers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'static_pages#home'
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
  get '/static_pages_aboutus', to: 'static_pages#aboutus'
  get '/static_pages_contactus', to: 'static_pages#contactus'

  get    '/login_admin',   to: 'sessions#adminLogin'
  post   '/login_admin',   to: 'sessions#create_admin'
  delete '/logout_admin',  to: 'sessions#destroy_admin'
  get '/logout_admin', to: 'sessions#destroy_admin'

  get '/destroy_booking/:id', to: 'bookings#destroy', as: 'destroy_booking'

  get '/destroy_libraryuser/:id', to: 'libraryusers#destroy', as: 'destroy_libraryuser'

  get '/destroy_admin/:id', to: 'admins#destroy', as: 'destroy_admin'

   get '/destroy_room/:id', to: 'rooms#destroy', as: 'destroy_room'

  get 'static_pages/home'
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :bookings
	validates :size, :presence=>true
	validates :building, :presence=>true
	validates :roomid, :presence=>true, :uniqueness => true
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :authorize_either
  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @bookings = Booking.all
    @bookings = @bookings.where(room_id: @room.id)
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy

    @bookings = Booking.all
    @bookings = @bookings.where(room_id: @room.id)
    for eachBooking in @bookings
      #destroy_booking_path eachBooking
      eachBooking.destroy
    end

    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:roomid, :size, :building)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for(room) do |f| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :roomid %>
    <%= f.number_field :roomid %>
  </div>

  <div class="field">
    <%= f.label :size %>
    <%= f.number_field :size %>
  </div>

  <div class="field">
    <%= f.label :building %>
    <%= f.text_field :building %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Roomid</th>
      <th>Size</th>
      <th>Building</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.roomid %></td>
        <td><%= room.size %></td>
        <td><%= room.building %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <% if admin_logged_in?%>
          <td><%= link_to 'Destroy',destroy_room_path(room),  data: { confirm: 'Are you sure?' } %></td>
        <% end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
  <p id="notice"><%= notice %></p>

<p>
  <strong>Roomid:</strong>
  <%= @room.roomid %>
</p>

<p>
  <strong>Size:</strong>
  <%= @room.size %>
</p>

<p>
  <strong>Building:</strong>
  <%= @room.building %>
</p>

<p> Booking history </p>

<p>All the time slots are 2 hour slots.</p>
<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.date %></td>
        <td><%= booking.start_time.hour%>:00</td>
        <td><%= booking.start_time.hour+2%>:00</td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>